### ISSUE TITLE
Legend Overlaps with graph

### ISSUE THREAD

**Issue by prakhar230792** [knowm/XChart#237]
I find that we do not have:
LegendPosition.OutsideN and
LegendPosition.OutsideW
legend positions.

Due to this legend overlaps with the chart I am trying to create. Attaching relevant image. 
![columnchartleftlegend](https://user-images.githubusercontent.com/10173765/33645167-6816c1be-da6f-11e7-924a-17491ae0bfe0.PNG)
![columncharttoplegend](https://user-images.githubusercontent.com/10173765/33645171-6adac030-da6f-11e7-9913-aa40d632b7a1.PNG)

However Legend Positions
LegendPosition.OutsideS and LegendPosition.OutsideE exists and work totally fine.

Is there any way that I can fix the overlap in the above two images ?

**Comment by timmolter** [comment]
There is no way to "fix" it. That's the way it is designed to work.

**Comment by hakantkn** [comment]
You can manually set max for y axis so that the top of the chart is empty. For example:   
```
     chart.addSeries("a very long series name", Arrays.asList(0, 1, 2, 3, 4, 5), Arrays.asList(35, 40, 38, 42, 5, -8));
     chart.getStyler().setYAxisMax(50.0);
```
See screen shots below:
![image](https://user-images.githubusercontent.com/6737748/33829299-bebac19a-de80-11e7-977d-1b036150b093.png)

![image](https://user-images.githubusercontent.com/6737748/33829310-c99ac9d4-de80-11e7-92e5-24181ec333e2.png)
