### ISSUE TITLE
Reference line in chart

### ISSUE THREAD

**Issue by agrypinie** [knowm/XChart#288]
I would be nice if there where a reference line in XChart, which shows a simple line (possible for max oder min values). Like this: [http://recharts.org/en-US/api/ReferenceLine](http://recharts.org/en-US/api/ReferenceLine). 

I need this feature for a multiple y-axis CategoryChart.

Or does this feature already exist?

**Comment by bernard01** [comment]
I am also interested in this feature from a different perspective. It is often important to record any events such as, in a stock chart, a buy event and a sell event. I am inspired by a feature in MATLAB / Octave where I saw in a paper that colored lines were used to record transaction events, with the line() function with parameters points and RGB color.

The line() function is shown on the Octave MATLAB clone page:
https://octave.sourceforge.io/octave/function/line.html

Importantly, this would need a matching command to remove all lines from a chart so that it works as an on-line chart as well.

Even if the line cannot have its own label, it would still be extremely useful because lines can be referred to by color in any custom legend separately.
![lineexample](https://user-images.githubusercontent.com/1733616/49067443-01d55680-f289-11e8-9d3e-c9ddbfa91e1e.png)
