### ISSUE TITLE
Demo not running on Win10

### ISSUE THREAD

**Issue by chjan** [knowm/XChart#347]
One of the best and most informative Readme I have seen. However:

1. Searching Github for BODE chart, frequency SPL and other keywords, the project did not show up. (Got the tip about Xchart from a friend). Perhaps add some search tags related to audio engineering, as it seems suitable for such tasks? Just a suggestion.

2. The command to start the demo I was unable run on Windows 10, regardless of using PowerShell or the good old terminal window. I tried with semi-colon. Any tips? It does not find the main class at the end of the line.

**Comment by vvdavid** [comment]
I also had this problem, I thought I was not executing the command properly, I googled how to run a jar correctly, tried a lot of ways with no success, I gave up after trying a several hours.

**Comment by Mr14huashao** [comment]
@chjan @vvdavid

**Comment by timmolter** [comment]
@vvdavid Can you please post what command you were using and what error came out??

**Comment by justin-umgc** [comment]
Having what I think is the same issue.  Downloaded the jar (tried 3.6.0 and 3.6.1). Changed to the directory containing the jar (using Powershell). Ran the command: 
  java -cp xchart-demo-3.6.0.jar:xchart-3.6.0.jar org.knowm.xchart.demo.XChartDemo
Error message:
  Error: Could not find or load main class org.knowm.xchart.demo.XChartDemo
  Caused by: java.lang.ClassNotFoundException: org.knowm.xchart.demo.XChartDemo

**Comment by timmolter** [comment]
@justin-umgc Thanks!
I've put instructions here: <https://knowm.org/open-source/xchart/xchart-example-code/>

**Comment by Mr14huashao** [comment]
Tested, execute `java -cp" xchart-demo-3.6.2-SNAPSHOT.jar; xchart-3.6.2-SNAPSHOT.jar "org.knowm.xchart.demo.XChartDemo in Powershell and CMD window on win10 `Command is OK.

**Comment by Mr14huashao** [comment]
@timmolter 
Usage has been added to the README, this issue can be closed.
