### ISSUE TITLE
Date ticks on X-axis do not align with start/end values in the plot line.

### ISSUE THREAD

**Issue by alw1746** [knowm/XChart#527]
For further details, pls see this [problem description](https://alw1746.github.io/projects/xchart/index.html)  

I have tried various styler options to no avail eg tick padding, plot size, etc. Any suggestions?

**Comment by timmolter** [comment]
OK, I could determine that it's not really a bug, but it's also not behaving as one would expect. I'm working on a fix. Thanks for reporting this.

**Comment by timmolter** [comment]
OK, there are two issues at play here.

1) the way that Java Date objects work is not as expected or intuitive. A `java.util.Date` has no internal timezone and always refers to UTC by spec. You cannot change it inside this object. Therefore you need to give a Date object a long value from the defined epoch relative to UTC. The SimpleDateFormatter uses the local time zone and ends up creating a Date object that is shifted by the number of hours you are from UTC. See the following code for how to deal with this.

<https://github.com/knowm/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/standalone/issues/TestForIssue527.java>

I need to update the API across all of XChart to use Java's new Time and Date API and get rid of Date. I'll do that some time in the future.

2) I added code changing the way that the axis tick labels are calculated so that there are no duplicates like you were reporting. You'll need to use the latest SNAPSHOT jar or wait for 3.7.1.

<img width="1280" alt="Screen Shot 2020-12-27 at 7 01 59 PM" src="https://user-images.githubusercontent.com/738972/103180414-d8d38580-4895-11eb-93fb-a860c7ac5312.png">
